# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.1.0"

Vagrant.configure(2) do |config|

  config.vm.hostname = "my-postgresql"
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.network "forwarded_port", guest: 5432, host: 5432 
  
  config.vm.provider :parallels do |p, override|
    override.vm.box = "parallels/ubuntu-14.04"
    p.check_guest_tools = false
    p.functional_psf    = false
    p.name = "my-postgresql"
  end
  
  config.vm.provision "shell" do |s|
    s.path = "install-postgresql.sh"
  end

end