# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.1.0"

Vagrant.configure(2) do |config|

  config.vm.hostname = "my-rabbitmq"
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.network "forwarded_port", guest: 5672, host: 5672 # AMQP 0-9-1 with TLS
  config.vm.network "forwarded_port", guest: 4369, host: 4369 # epmd
  config.vm.network "forwarded_port", guest: 25672, host: 25672 # Erlang distribution   
  config.vm.network "forwarded_port", guest: 15672, host: 15672 # Managemant plugin   
  
  config.vm.provider :parallels do |p, override|
    override.vm.box = "parallels/ubuntu-14.04"
    p.check_guest_tools = false
    p.functional_psf    = false
    p.name = "my-rabbitmq"
  end
  
  config.vm.provision "shell" do |s|
    s.path = "install-rabbitmq.sh"
  end
  
end